# Generated by Django 4.2 on 2024-09-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra_elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('inversion', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'elementos_comprados',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=100)),
                ('price_buy', models.FloatField()),
                ('price_sell', models.FloatField()),
                ('cant_inventor', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'elemento',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto_total', models.FloatField(default=0)),
                ('ganancia', models.FloatField(default=0)),
                ('elementos', models.ManyToManyField(to='inventario.compra_elemento')),
            ],
            options={
                'db_table': 'elementos_vendidos',
            },
        ),
        migrations.AddField(
            model_name='compra_elemento',
            name='elementos',
            field=models.ManyToManyField(to='inventario.element'),
        ),
    ]
