# Generated by Django 4.2 on 2024-09-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_compra_rename_monto_total_venta_cantidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='cant_inventor',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='element',
            old_name='element_name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='element',
            old_name='price_buy',
            new_name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='element',
            name='price_sell',
        ),
        migrations.AddField(
            model_name='element',
            name='precio_venta',
            field=models.FloatField(default=0),
        ),
    ]
