# Generated by Django 4.2 on 2024-09-27 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_rename_cant_inventor_element_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='elemento',
        ),
        migrations.AddField(
            model_name='compra',
            name='elemento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.element'),
        ),
    ]
