# Generated by Django 4.2 on 2024-10-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_compra_elemento_compra_elemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
