# Generated by Django 4.2 on 2024-10-02 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_compra_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='venta',
            name='elemento',
        ),
        migrations.AddField(
            model_name='venta',
            name='elemento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.element'),
        ),
    ]
