# Generated by Django 4.2 on 2024-10-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_venta_cantidad_remove_venta_elemento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='ganancia',
            field=models.IntegerField(default=0),
        ),
    ]
