# Generated by Django 4.2 on 2024-10-02 02:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_venta_ganancia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_operacion', models.DateField(default=datetime.date.today)),
                ('operacion', models.CharField()),
                ('cantidad', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'operacion',
            },
        ),
        migrations.AlterField(
            model_name='element',
            name='precio_compra',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='element',
            name='precio_venta',
            field=models.IntegerField(default=0),
        ),
    ]
