# Generated by Django 4.2 on 2024-10-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_operacion_alter_element_precio_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='inversion',
            field=models.IntegerField(default=0),
        ),
    ]
