# Generated by Django 4.2 on 2024-10-03 22:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_compra_inversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vale_compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_elementos', models.IntegerField()),
                ('inversion_total', models.IntegerField(default=0)),
                ('fecha_compra', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'lista_compras',
            },
        ),
        migrations.CreateModel(
            name='Vale_venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_elementos', models.IntegerField(default=0)),
                ('monto_vendido', models.IntegerField(default=0)),
                ('ganancia_total', models.IntegerField(default=0)),
                ('fecha_venta', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'lista_ventas',
            },
        ),
        migrations.RemoveField(
            model_name='compra',
            name='fecha_compra',
        ),
        migrations.AddField(
            model_name='compra',
            name='vale_compra',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventario.vale_compra'),
        ),
        migrations.AddField(
            model_name='venta',
            name='vale_venta',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventario.vale_venta'),
        ),
    ]
