# Generated by Django 4.2 on 2024-10-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_vale_compra_vale_venta_remove_compra_fecha_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vale_compra',
            name='cantidad_elementos',
            field=models.IntegerField(default=0),
        ),
    ]
